
/* Animals */

insert into animal VALUES
(1, "Pandas","The giant panda (Ailuropoda melanoleuca), also known as the panda bear is characterised by its bold black-and-white coat and rotund body. The name giant panda is sometimes used to distinguish it from the red panda, a neighboring musteloid. They weigh 120-150 kg and its height is 170-180 cm.",'img/1.jpg');
(2, "Camel","A camel (from: Latin: camelus)  is an even-toed ungulate in the genus Camelus that bears distinctive fatty deposits known as humps on its back. Camels have long been domesticated and, as livestock, they provide food (milk and meat) and textiles (fiber and felt from hair). Camels usually weigh between 600 and 1000 kg and their height is around 1.80 m.", 'img/2.jpg');
(3, "Zebra"," Zebras (Hippotigris) are African equines with distinctive black-and-white striped coats. There are three living species: the Grévy's zebra (Equus grevyi), plains zebra (E. quagga), and the mountain zebra. Zebras weight is between 160 and 385 kg and its height is 217-240 cm.", 'img/3.jpg');
(4, "Asiatic lion","The Asiatic lion is a population of Panthera leo leo that today survives in the wild only in India. The Asiatic lion's fur ranges in colour from ruddy-tawny, heavily speckled with black, to sandy or buffish grey, sometimes with a silvery sheen in certain lighting. Asiatic lions weigh between 110 and 190 kg and their height is 1.10-1.40m.", 'img/4.jpg');
(5, "Giraffe","The giraffe is a large African hoofed mammal belonging to the genus Giraffa. It is the tallest living terrestrial animal and the largest ruminant on Earth. Traditionally, giraffes were thought to be one species, Giraffa camelopardalis, with nine subspecies. Giraffes usually weigh around 1400 kg and their height, 6m.", 'img/5.jpg');
(6, "Elephant","Elephants are the largest existing land animals. Three living species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant. Elephants are found in different habitats, including savannahs, forests, deserts, and marshes. They are herbivorous, and they stay near water when it is accessible. They weigh between 100 and 6000 kg and their height is 2-3.5 m. ", 'img/6.jpg');
(7, "Owl","The Eurasian eagle-owl (Bubo bubo) is a species of eagle-owl that resides in much of Eurasia. It is also called the Uhu and it is occasionally abbreviated to just the eagle-owl in Europe. It is one of the largest species of owl, and females can grow to a total length of 75 cm (30 in), with a wingspan of 188 cm (6 ft 2 in), with males being slightly smaller.", 'img/7.jpg');
(8, "Dolphin","Oceanic dolphins or Delphinidae are a widely distributed family of dolphins that live in the sea. Close to forty extant species are recognised. They include several big species whose common names contain whale rather than dolphin, such as the Globicephalinea. Oceanic dolphins range in size from the 1.7-metre-long (5 ft 7 in) and 50-kilogram (110-pound) Maui's dolphin to the 9.4-metre (31 ft) and 10-metric-ton (11-short-ton) orca, the largest known dolphin.", 'img/8.jpg');


